### ISSUE TITLE
[New Ideas] Still active?

### ISSUE THREAD

**Issue by YeonV** [michalochman/react-web-audio-graph#11]
AMAZING project BROOO!!!!
I have a lot of ideas to add, are you open for suggestions? Is this still an active project?

Thank you soo much for this wonderful piece!!

**Comment by michalochman** [comment]
Hi @YeonV, feel free to suggest improvements as separate "issues". We can take it from there.

**Comment by YeonV** [comment]
> Hi @YeonV, feel free to suggest improvements as separate "issues". We can take it from there.

Hi @michalochman , thank you so much for your super fast answer <3
Currently im developing the new frontend for LedFx and a wled-manager.
Both are playing with audio-to-light, that's why I have soo many ideas for your amazing project.
I added some already :)

If you wanna have more informations or you like to team up for new ideas or just chat about, 
we can meet in discord: https://discord.gg/zHq8bHre
(invite link valid for 1day, can resend you anytime)
