### ISSUE TITLE
[Extend Feature]: Destination - New Type

### ISSUE THREAD

**Issue by YeonV** [michalochman/react-web-audio-graph#14]
Hi Bro!

Can you somehow create a new Destination-Type: `network` ?
So we can send packages over network:
 - TCP
 - Websocket
 - UDP (if inside electron for example)
 - maybe choose between different package-types aswell

I feel this must be a big one, but it would really be a complete game-changer <3

**Comment by michalochman** [comment]
What would be the use case for that?

Not sure how this can be achieved and what would be the data format for such transmission.

You can probably push data to an audio buffer, read from there and do anything you want with the data.

**Comment by YeonV** [comment]
I want to do music to light:
https://user-images.githubusercontent.com/28861537/153004454-ea2f8993-c34f-4059-a1c3-a8ccde045e6d.mp4

> You can probably push data to an audio buffer, read from there and do anything you want with the data.

How would that work? Sounds promising :)

i think that a network output is too hard to implement, but if you think its doable,
then it could look like:
Destination -> Network:
```js
{
  host: string
  pixel_count: number,
  type: 'ws' | 'tcp' | 'udp',
  data: array  // (length: pixel_count * 3),
  effect: string // entrypoint to build effects later; maybe better as seperate node
}
```

example:  sending red to a 3-led-strip

```js
{
  host: 'http://192.168.1.5/ws'
  pixel_count: 3,
  type: 'ws' | 'tcp' | 'udp',
  data: [255,0,0,255,0,0,255,0,0], // this changes depending on incoming audio
  effect: 'default' 
}
```

**Comment by michalochman** [comment]
Looking at available Web APIs and what you need might be possible with:
* [MediaStream Recording API](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API)
* [MediaRecorder](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder)
